### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by imoo12138** [irishev/DSP#3]
i tried to run your code follow your instructions with the cifar10  , and  impressived by the acceleration ,but the accuracy is not good  as well as yours. any advice would  be appreciate !

**Comment by irishev** [comment]
Would you provide more detailed information? Are you training from scratch? Or, are you running inferences with released checkpoints?

**Comment by imoo12138** [comment]
i  trained from scratch , and the accuracy of resnet18 with cifar10 dataset could  get  about 92% after trainning ,  then i  run  the cifar_dsp which got an accuracy  at about 70%  ,  after that i run  the cifar_finetune and got a  accuracy at 81% only. So, i  have no idea how to fix it.

**Comment by irishev** [comment]
That might be because the regularization is too strong. In our experiments, we found that adjusting the regularization power, specified by "-r [value]" in the code, inversely proportionally to the number of model parameters is beneficial in obtaining optimal efficiency. We used 2e-3 for 0.27M parameters, so we can use 5e-5 for resnet18 with 11.4M parameters.

It is noteworthy that the regularization power may interact with other regularization techniques like L2 decay. It is recommended to try several values other than 5e-5 to find the best configurations.
